In [2]:
# Задание 1
# Используем файл keywords.csv.
 
# Необходимо написать гео-классификатор, который каждой строке сможет выставить географическую 
# принадлежность определенному региону. Т. е. если поисковый запрос содержит название города региона, 
# то в столбце 'region' пишется название этого региона. Если поисковый запрос не содержит названия города, 
# то ставим 'undefined'.
 
# Правила распределения по регионам Центр, Северо-Запад и Дальний Восток:
 
geo_data = {
 
    'Центр': ['москва', 'тула', 'ярославль'],
 
    'Северо-Запад': ['петербург', 'псков', 'мурманск'],
 
    'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
 
}
 
# Результат классификации запишите в отдельный столбец region.

In [3]:
import pandas as pd

In [201]:
# заливаем данные в датафрейм
data = pd.read_csv('keywords.csv')

# проставляем индексы для каждой строки (пригодилось при проверке)
data_1 = data.reset_index()

# зная, что в файле встречается мало строк с нужной нам информацией - сразу проставляю undefined для всех
data_1['location'] = 'undefined'

# length - количество строк в датафрейме
length =len(data_1['keyword'])

# поигрался с данными, подождал после запуска, понял, что не отработает быстро, поэтому взял первые 2000 строк для обработки
for line in range(2000):
   
    # смотрю по слоарю - значения для каждого ключа
    for loca in geo_data:
        
        # смотрю по каждому значению ключа словаря
        for city in geo_data[loca]:
            
            # проверка: если хотя бы оно значение ключа содержится в строке,  
            if(city in data_1['keyword'][line]):
                
                # в этой строке значение undefined заменяю на название ключа словаря
                data_1['location'][line] = loca
                
                # тут как раз индекс мне и помог определить, где в како строке есть искомое значение
                print(data_1['location'][line],data_1['index'][line])
                
# взял значения индексов, где попадаются значения ключа словаря
data_1[1235:1260]

C:\Users\Idea\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

Центр 127
Северо-Запад 370
Северо-Запад 564
Центр 849
Дальний Восток 1063
Северо-Запад 1236
Центр 1259
Северо-Запад 1346
Центр 1396
Центр 1482
Центр 1579
Центр 1682

,index,keyword,shows,location
1235,1235,три кота,155975,undefined
1236,1236,банк санкт петербург,174375,Северо-Запад
1237,1237,санлайт,155484,undefined
1238,1238,айфон 7,159426,undefined
1239,1239,купить билет на самолет,158679,undefined
1240,1240,uchi ru,155226,undefined
1241,1241,google chrome,156086,undefined
1242,1242,пгу мос,173971,undefined
1243,1243,лучшие фильмы 2015 2016,159124,undefined
1244,1244,губка боб квадратные штаны мультсериал,155526,undefined
1245,1245,яндекс новости,216769,undefined
1246,1246,почта россии отслеживание почтовых отправлений,162037,undefined
1247,1247,дром алтайский край,154940,undefined
1248,1248,скуби ду,154376,undefined
1249,1249,иллюзия обмана 2 фильм 2016,156132,undefined
1250,1250,прибытие фильм 2016,154524,undefined
1251,1251,ютюб,154014,undefined
1252,1252,мара багдасарян,167225,undefined
1253,1253,гримм,153880,undefined
1254,1254,мэйл ру,153806,undefined
1255,1255,кинопрофи,153733,undefined
1256,1256,русский секс,192086,undefined
1257,1257,головоломка мультфильм 2015,153261,undefined
1258,1258,григорий распутин,155624,undefined
1259,1259,москва,153050,Центр

In [ ]:
# Задание 2
# Напишите функцию, которая классифицирует фильмы из материалов занятия по следующим правилам:
# - оценка 2 и меньше - низкий рейтинг
# - оценка 4 и меньше - средний рейтинг
# - оценка 4.5 и 5 - высокий рейтинг

# Результат классификации запишите в столбец class

In [75]:
# функция для поиска соответствий
def class_x(x):
    
    # переменная строкового типа для записи в неё значения классификатора
    rez = ''
    if(x<=2):
        rez = 'low rating'
    else:
        if(x<=4):
            rez = 'mid rating'
        else:
            rez = 'high rating'
    return rez

# функция добавляет столбец с классификацией по рейтингу
def classificator(data):
    data['class'] = data['rating'].apply(lambda x: class_x(x))
    return data   

# считываю данные из файла в датафрейм
movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')

# создаю сводную таблицу
joined = movies.merge(ratings, on='movieId')

# использую функцию классификатора
a = classificator(joined)
a.head()

,movieId,title,genres,userId,rating,timestamp,class
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,3.0,851866703,mid rating
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,9,4.0,938629179,mid rating
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,13,5.0,1331380058,high rating
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.0,997938310,low rating
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,19,3.0,855190091,mid rating

In [ ]:
# Задание 3
# Посчитайте среднее значение Lifetime киноманов (пользователи, которые поставили 100 и более рейтингов). 
# Под Lifetime понимается разница между максимальным и минимальным значением timestamp для каждого 
# пользователя. Ответ дайте в днях.

In [200]:
# считаею количество оценок каждого пользователя
num_of_rates = ratings.groupby('userId').agg({'timestamp':'count'}).reset_index()

# записываю пользователей, у которых болььше 100 оценок
more_than_100_rates = num_of_rates[num_of_rates.timestamp>=100]

# назначаю удобные названия колнкам
more_than_100_rates.columns = ['userId','num_of_rates']

# дополняю таблицу значениями из ratings
more_than_100_rates_Full = more_than_100_rates.merge(ratings, on='userId', how='left')

# ищу для каждого пользователя последнее время оценки на сайте
fresh_timestamp = more_than_100_rates_Full.groupby('userId').agg({'timestamp':['min']}).reset_index()

# назначаю удобные названия колнкам
fresh_timestamp.columns = ['userId','l_time']

#дополняю полную таблицу колонкой времен, когда пользователь последниц раз ставил оценки
final_table = more_than_100_rates_Full.merge(fresh_timestamp, on='userId', how='left')

# вычитаю значение времени последнего оценивания из времени самого давнего оценивания 
final_table['difference'] = final_table['timestamp'] - final_table['l_time']

# ищу среднее значение полученных результатов для каждого пользователя
final_table_average_mean = final_table.groupby('userId').agg({'difference':'mean'}).reset_index()

# создаю еще 1 колонку для удобства, в которую запишу эти данные в виде полных дней
final_table_average_mean['in_days'] = final_table_average_mean['difference'].apply(lambda x: int(x/86400))

# вывод на экран
final_table_average_mean.head()

   userId    difference  in_days
0       4  1.018771e+05        1
1       5  1.050170e+03        0
2       8  4.849204e+04        0
3      15  1.897945e+08     2196
4      17  2.764102e+03        0

In [178]:
# Задание 4
# Есть мнение, что "раньше снимали настоящее кино, не то что сейчас". Ваша задача проверить это утверждение, 
# используя файлы с рейтингами фильмов из материалов занятия. Т. е. проверить верно ли, что с ростом года 
# выпуска фильма его средний рейтинг становится ниже.
 
# При этом мы не будем затрагивать субьективные факторы выставления этих рейтингов, а пройдемся по следующему 
# алгоритму:
 
# 1. В переменную years запишите список из всех годов с 1950 по 2010.
 
# 2. Напишите функцию production_year, которая каждой строке из названия фильма выставляет год выпуска. 
# Не все названия фильмов содержат год выпуска в одинаковом формате, поэтому используйте следующий алгоритм:
# - для каждой строки пройдите по всем годам списка years
# - если номер года присутствует в названии фильма, то функция возвращает этот год как год выпуска
# - если ни один из номеров года списка years не встретился в названии фильма, то возвращается 1900 год
 
# 3. Запишите год выпуска фильма по алгоритму пункта 2 в новый столбец 'year'
 
# 4. Посчитайте средний рейтинг всех фильмов для каждого значения столбца 'year' и отсортируйте результат 
# по убыванию рейтинга

In [ ]:
# Если Вы это увидели, значит на момент дедлайна по сдаче, видимо, я не успел сделать 4 задание ¯\_(ツ)_/¯